### 회원가입
POST http://localhost:8080/auth/join
Content-Type: application/json

{
  "username": "part1",
  "password": "1q2w3e4r!",
  "nickname": "위콘1",
  "phoneNumber": "0102132147"
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "manager1",
  "password": "1q2w3e4r!"
}

> {%
  client.global.set("accessToken", response.headers.valueOf("Authorization"))
  client.log("엑세스 토큰: " + client.global.get("accessToken"));
%}


### 네이버 로그인 테스트(인증코드로 요청)
POST http://localhost:8080/auth/naver
Content-Type: text/plain


### 네이버 로그인 필터 테스트
POST http://localhost:8080/auth/oauth2/login
Content-Type: application/json

{
  "registrationId": "naver",
  "authorizationCode": "VtEIvX59f6cEbZmBwq"
}

### 카카오 로그인 필터 테스트
POST http://localhost:8080/auth/oauth2/login
Content-Type: application/json

{
  "registrationId": "kakao",
  "authorizationCode": "rY0ijkxxrIgHpWBFPZteh-Ur0DYby7pypAoC9MVIkTwUAdwr9-WxE6dT3OwKPXWaAAABjX-XxTH-oZq-Jypvmw"
}

