### 채팅방 생성
POST http://localhost:8080/chatRoom
Content-Type: application/json
Authorization: {{accessToken}}

{
  "memberId": 8,
  "name": "8번채팅방",
  "tags": ["#3번", "#6번", "#10번"]
}

### 채팅방 조회
GET http://localhost:8080/chatRoom
Content-Type: application/json

### 채팅방 입장
GET http://localhost:8080/chatRoom/5/enter
Content-Type: application/json
Authorization: {{accessToken}}

### 채팅방 퇴장
DELETE http://localhost:8080/chatRoom/3/exit
Content-Type: application/json
Authorization: {{accessToken}}
