### 태그 정보 조회(태그 갯수가 많은 순으로 정렬)
GET http://localhost:8080/tag/search
Content-Type: application/json


### 태그 이름 검색(태그 갯수가 많은 순으로 정렬)
< {%
  request.variables.set("tags", "위드")
%}
GET http://localhost:8080/tag/{{tags}}/search
Content-Type: application/json

### 태그 자동완성
< {%
  request.variables.set("keyword", "수")
%}
GET http://localhost:8080/tag/search?performance=1&keyword={{keyword}}
Content-Type: application/json