spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/withcon?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zerobase

  jpa:
    show-sql: true
    database: mysql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

