version: '3.1'

services:
  jenkins:
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - /home/ec2-user/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - withcon

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/ec2-user/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - withcon

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - withcon

networks:
  withcon:
    driver: bridge