version: '3.1'

services:
  withcon-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: withcon-mysql
    env_file:
      - /home/ec2-user/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/ec2-user/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - withcon

  withcon-nginx:
    image: nginx:latest
    container_name: withcon-nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - withcon

networks:
  withcon:
    driver: bridge